/**
 * organizationCategories
 *
 * enum
 *
 * Represents all categories that an organization can be a part of.
 */
module.exports = {
  RESTAURANT: {
    name: 'Restaurant, Bar, Cafe',
    description: 'Education about and access to venture funding',
    image: 'capital',
    identifier: 'capital',
    color: '#7B3F23',
    bgColor: '#e5d7cf',
  },
  HEALTHCARE: {
    name: 'Healthcare & Wellness',
    description: 'DU student clubs and Denver-based non-profits',
    image: 'clubsAndOrganizations',
    identifier: 'clubs_and_organizations',
    color: '#7D6D26',
    bgColor: '#e2dec9',
  },
  BREWERY_DISTILLERY: {
    name: 'Brewery, Distillery',
    description: 'Places to work and venues to host events',
    image: 'coworkingSpaces',
    identifier: 'coworking_spaces',
    color: '#5D7C26',
    bgColor: '#d9e2c9',
  },
  COWORKING_SPACES: {
    name: 'Coworking/Business-related ',
    description: 'Places to work and venues to host events',
    image: 'coworkingSpaces',
    identifier: 'coworking_spaces',
    color: '#5D7C26',
    bgColor: '#d9e2c9',
  },
  FITNESS_GYM: {
    name: 'Fitness/Gym',
    description: 'Classes, advising, and academic resources',
    image: 'curriculum',
    identifier: 'curriculum',
    color: '#257D6E',
    bgColor: '#cbe3df',
  },
  RETAIL_OTHER: {
    name: 'Retail: Other',
    description: 'Places to meet, learn, and collaborate',
    image: 'events',
    identifier: 'events',
    color: '#225D7B',
    bgColor: '#cedde5',
  },
  PET_ANIMAL: {
    name: 'Pet & Animal Care',
    description: 'Awesome organizations dedicated to innovation',
    image: 'innovationPartners',
    identifier: 'innovation_partners',
    color: '#3F237A',
    bgColor: '#dbd4e8',
  },
  HOUSEHOLD: {
    name: 'Household',
    description: 'Learn, engage, and utilize',
    image: 'programsAndResources',
    identifier: 'programsAndResources',
    color: '#7B225C',
    bgColor: '#e7d3e0',
  },
  RETAIL_FOOD_DRINK: {
    name: 'Retail: Food & Drink',
    description: 'Learn, engage, and utilize',
    image: 'programsAndResources',
    identifier: 'programsAndResources',
    color: '#7B225C',
    bgColor: '#e7d3e0',
  },
  ENTERTAINMENT: {
    name: 'Entertainment',
    description: 'Learn, engage, and utilize',
    image: 'programsAndResources',
    identifier: 'programsAndResources',
    color: '#7B225C',
    bgColor: '#e7d3e0',
  },
  EDUCATION: {
    name: 'Education',
    description: 'Learn, engage, and utilize',
    image: 'programsAndResources',
    identifier: 'programsAndResources',
    color: '#7B225C',
    bgColor: '#e7d3e0',
  },
  FOR_KIDS: {
    name: 'For Kids',
    description: 'Learn, engage, and utilize',
    image: 'programsAndResources',
    identifier: 'programsAndResources',
    color: '#7B225C',
    bgColor: '#e7d3e0',
  },
  NONPROFITS: {
    name: 'Nonprofits/Consulting',
    description: 'Learn, engage, and utilize',
    image: 'programsAndResources',
    identifier: 'programsAndResources',
    color: '#7B225C',
    bgColor: '#e7d3e0',
  },
  OTHER: {
    name: 'Other',
    description: 'Meet with other individuals in the community',
    image: 'meetups',
    identifier: 'meetups',
    color: '#7c1f2d',
    bgColor: '#e8d3d6',
  },
// };
// module.exports = {
  CAPITAL: {
    name: 'Capital',
    description: 'Education about and access to venture funding',
    image: 'capital',
    identifier: 'capital',
    color: '#7B3F23',
    bgColor: '#e5d7cf',
  },
  CLUBS_AND_ORGANIZATIONS: {
    name: 'Clubs & Organizations',
    description: 'DU student clubs and Denver-based non-profits',
    image: 'clubsAndOrganizations',
    identifier: 'clubs_and_organizations',
    color: '#7D6D26',
    bgColor: '#e2dec9',
  },
  COWORKING_SPACES: {
    name: 'Coworking Spaces',
    description: 'Places to work and venues to host events',
    image: 'coworkingSpaces',
    identifier: 'coworking_spaces',
    color: '#5D7C26',
    bgColor: '#d9e2c9',
  },
  CURRICULUM: {
    name: 'Curriculum',
    description: 'Classes, advising, and academic resources',
    image: 'curriculum',
    identifier: 'curriculum',
    color: '#257D6E',
    bgColor: '#cbe3df',
  },
  EVENTS: {
    name: 'Events',
    description: 'Places to meet, learn, and collaborate',
    image: 'events',
    identifier: 'events',
    color: '#225D7B',
    bgColor: '#cedde5',
  },
  INNOVATION_PARTNERS: {
    name: 'Innovation Partners',
    description: 'Awesome organizations dedicated to innovation',
    image: 'innovationPartners',
    identifier: 'innovation_partners',
    color: '#3F237A',
    bgColor: '#dbd4e8',
  },
  PROGRAMS_AND_RESOURCES: {
    name: 'Programs & Resources',
    description: 'Learn, engage, and utilize',
    image: 'programsAndResources',
    identifier: 'programsAndResources',
    color: '#7B225C',
    bgColor: '#e7d3e0',
  },
  MEETUPS: {
    name: 'Meetups',
    description: 'Meet with other individuals in the community',
    image: 'meetups',
    identifier: 'meetups',
    color: '#7c1f2d',
    bgColor: '#e8d3d6',
  },
};
